import React from 'react';
import { 
  Target, 
  Rocket, 
  TrendingUp,
  Shield,
  Users,
  CheckCircle,
  BarChart3,
  DollarSign,
  Zap,
  Globe,
  Building,
  Award,
  AlertTriangle,
  Lightbulb,
  Scale,
  Leaf,
  Heart,
  Brain,
  Eye,
  Clock,
  Star,
  ArrowRight,
  Activity,
  Briefcase,
  Settings,
  BookOpen,
  PieChart
} from 'lucide-react';
import './EntrepreneurshipPage.css';

export default function EntrepreneurshipPage() {
  const kpiCategories = [
    {
      title: "Regulatory and Quality KPIs",
      icon: Shield,
      color: "blue",
      metrics: [
        { name: "Regulatory Compliance Rate", description: "Percentage of successful audits and inspections without violations" },
        { name: "Complaint Rate", description: "Number of customer complaints per 1,000 devices sold" },
        { name: "Device Defect Rate", description: "Frequency of device malfunctions or nonconformities per production batch" },
        { name: "CAPA Effectiveness", description: "Percentage of corrective and preventive actions that permanently resolve identified issues" }
      ]
    },
    {
      title: "Product and Clinical KPIs",
      icon: Heart,
      color: "emerald",
      metrics: [
        { name: "Diagnostic Accuracy Rate", description: "Proportion of accurate test results compared to total tests conducted" },
        { name: "Clinical Trial Success Rate", description: "Percentage of clinical studies achieving predefined safety, sensitivity, and specificity benchmarks" },
        { name: "Limit of Detection (LoD) Consistency", description: "Variability in LoD values across validated production batches" }
      ]
    },
    {
      title: "Commercial and Market KPIs",
      icon: DollarSign,
      color: "purple",
      metrics: [
        { name: "Market Adoption Rate", description: "Percentage of target customers or institutions adopting Opio-RX within a specified timeframe" },
        { name: "Sales per Product Line", description: "Revenue generated by each device configuration or deployment model" },
        { name: "Gross Profit Margin", description: "(Revenue − Cost of Goods Sold) ÷ Revenue, expressed as a percentage" },
        { name: "Customer Retention Rate", description: "Share of clients who reorder consumables or renew service agreements" },
        { name: "Customer Acquisition Cost (CAC)", description: "Total marketing and sales expenditure per new customer acquired" }
      ]
    },
    {
      title: "Operational KPIs",
      icon: Settings,
      color: "orange",
      metrics: [
        { name: "Manufacturing Yield", description: "Percentage of successfully produced units meeting all specifications" },
        { name: "On-Time Delivery Rate", description: "Orders fulfilled within the promised delivery schedule" },
        { name: "Inventory Turnover Ratio", description: "Efficiency of stock management and material utilization cycles" },
        { name: "Customer Service Response Time", description: "Average time taken to close technical or support queries" }
      ]
    },
    {
      title: "Strategic and Innovation KPIs",
      icon: Lightbulb,
      color: "cyan",
      metrics: [
        { name: "Time to Market", description: "Duration from R&D initiation to regulatory approval and commercial launch" },
        { name: "Device Utilization Rate", description: "Actual frequency of device use relative to expected operational capacity" },
        { name: "R&D Productivity Index", description: "Ratio of successful prototypes to total R&D projects undertaken" },
        { name: "Intellectual Property (IP) Growth Rate", description: "Number of new patents, trade secrets, or technology disclosures filed per year" }
      ]
    }
  ];

  const pestleFactors = [
    {
      title: "Political Factors",
      icon: Building,
      color: "red",
      points: [
        "Government funding emphasis on combating opioid epidemic supports rapid diagnostic technologies",
        "Partnerships with law enforcement, public health agencies, and emergency responders",
        "Compliance with international drug control treaties (UN conventions) shapes deployment standards"
      ]
    },
    {
      title: "Economic Factors",
      icon: DollarSign,
      color: "green",
      points: [
        "Lower per-test costs vs. GC-MS enables scalable deployment in resource-limited settings",
        "Efficient production of aptamers and AuNP components supports competitive pricing",
        "Insurance reimbursement policies influence clinical adoption rates"
      ]
    },
    {
      title: "Social Factors",
      icon: Users,
      color: "blue",
      points: [
        "Rising societal concern about synthetic opioid abuse drives demand for rapid detection",
        "Non-invasive testing reduces stigma and improves public acceptance",
        "Informed consent and data privacy critical for maintaining community trust"
      ]
    },
    {
      title: "Technological Factors",
      icon: Brain,
      color: "purple",
      points: [
        "Aptamer engineering ensures high specificity for synthetic opioids",
        "FRET-AuNP paper-based platform with AI-powered quantification for point-of-care use",
        "Smartphone integration potential enhances field usability and data connectivity",
        "Stability optimization critical for shelf-life and storage under varied conditions"
      ]
    },
    {
      title: "Legal Factors",
      icon: Scale,
      color: "yellow",
      points: [
        "FDA clearance and CE marking required for medical device commercialization",
        "Legal frameworks for law enforcement use, including data admissibility standards",
        "Patent protection for aptamer sequences and biosensor designs",
        "HIPAA and GDPR compliance for patient data protection"
      ]
    },
    {
      title: "Environmental Factors",
      icon: Leaf,
      color: "emerald",
      points: [
        "Biodegradable paper substrates promote eco-friendly device lifecycle",
        "Reduced chemical reagent use and toxic waste vs. laboratory methods",
        "Low-power optical detection minimizes environmental footprint",
        "Potential for monitoring opioid contamination in water and soil"
      ]
    }
  ];

  const getColorClasses = (color) => {
    const colorMap = {
      blue: { bg: "ent-blue-bg", border: "ent-blue-border", text: "ent-blue-text", accent: "ent-blue-accent" },
      emerald: { bg: "ent-emerald-bg", border: "ent-emerald-border", text: "ent-emerald-text", accent: "ent-emerald-accent" },
      purple: { bg: "ent-purple-bg", border: "ent-purple-border", text: "ent-purple-text", accent: "ent-purple-accent" },
      orange: { bg: "ent-orange-bg", border: "ent-orange-border", text: "ent-orange-text", accent: "ent-orange-accent" },
      cyan: { bg: "ent-cyan-bg", border: "ent-cyan-border", text: "ent-cyan-text", accent: "ent-cyan-accent" },
      red: { bg: "ent-red-bg", border: "ent-red-border", text: "ent-red-text", accent: "ent-red-accent" },
      green: { bg: "ent-green-bg", border: "ent-green-border", text: "ent-green-text", accent: "ent-green-accent" },
      yellow: { bg: "ent-yellow-bg", border: "ent-yellow-border", text: "ent-yellow-text", accent: "ent-yellow-accent" }
    };
    return colorMap[color] || colorMap.blue;
  };

  return (
    <div className="ent-page">
      {/* Hero Section */}
      <section className="ent-hero">
        <div className="ent-hero-bg"></div>
        <div className="ent-hero-decoration">
          <div className="ent-hero-blob ent-hero-blob-1"></div>
          <div className="ent-hero-blob ent-hero-blob-2"></div>
        </div>
        
        <div className="ent-hero-content">
          <div className="ent-badge">
            <Briefcase className="ent-badge-icon" />
            Business Strategy & Innovation
          </div>
          
          <h1 className="ent-hero-title">
            Entrepreneurship
          </h1>
          <h2 className="ent-hero-subtitle">
            Building the Future of Opioid Detection
          </h2>
          <p className="ent-hero-description">
            Strategic vision, measurable performance, and comprehensive market analysis 
            driving sustainable innovation in healthcare technology
          </p>
        </div>
      </section>

      <div className="ent-container">
        {/* Vision & Mission Section */}
        <section className="ent-section">
          <div className="ent-grid-2">
            {/* Vision */}
            <div className="ent-card ent-vision-card">
              <div className="ent-card-header">
                <h3 className="ent-card-title">
                  <Eye className="ent-card-icon ent-blue-text" />
                  Vision
                </h3>
              </div>
              <div className="ent-card-content">
                <p className="ent-card-text">
                  To become the trusted global standard in opioid detection technology, recognized for pioneering 
                  multiplex diagnostic platforms that blend scientific excellence with commercial viability. 
                  Opio-Rx aims to transform public health and safety by providing data-driven insights that enable 
                  proactive interventions and sustainable reductions in opioid-related harm worldwide.
                </p>
              </div>
            </div>

            {/* Mission */}
            <div className="ent-card ent-mission-card">
              <div className="ent-card-header">
                <h3 className="ent-card-title">
                  <Target className="ent-card-icon ent-purple-text" />
                  Mission
                </h3>
              </div>
              <div className="ent-card-content">
                <p className="ent-card-text">
                  To deliver industry-leading, scalable biosensors for rapid, on-site synthetic opioid detection 
                  that empower healthcare providers, emergency responders, and public safety organizations globally. 
                  We are committed to accelerating market adoption through strategic partnerships and innovative 
                  technology that drives measurable improvements in patient outcomes, operational efficiency, and 
                  regulatory compliance.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Unmet Needs vs Solution Section */}
        <section className="ent-section">
          <div className="ent-card ent-solution-card">
            <div className="ent-card-header">
              <h3 className="ent-card-title ent-center">
                <Zap className="ent-card-icon ent-cyan-text" />
                Problem & Solution Overview
              </h3>
              <p className="ent-card-subtitle">
                Bridging the critical gap between urgent healthcare needs and innovative biosensor solutions
              </p>
            </div>
            <div className="ent-card-content">
              <div className="ent-solution-content">
                <div className="ent-solution-image-container">
                  <div className="ent-solution-bg"></div>
                  <div className="ent-solution-decoration">
                    <div className="ent-solution-blob ent-solution-blob-1"></div>
                    <div className="ent-solution-blob ent-solution-blob-2"></div>
                  </div>
                  
                  <div className="ent-solution-image">
                    <img 
                      src="/images/entrepreneurship/entreimg1.png"
                      alt="OPIO-RX: From Unmet Needs to Solution - Addressing synthetic opioid overdose crisis with rapid, multiplex saliva biosensor technology"
                      className="ent-image"
                    />
                  </div>
                </div>
                
                {/* Key highlights below the image */}
                <div className="ent-grid-2 ent-mt-8">
                  <div className="ent-highlight-card ent-challenges">
                    <div className="ent-highlight-header">
                      <AlertTriangle className="ent-highlight-icon ent-red-text" />
                      <h4 className="ent-highlight-title ent-red-text">Critical Challenges</h4>
                    </div>
                    <ul className="ent-highlight-list">
                      <li>• Synthetic opioid overdose crisis</li>
                      <li>• Slow lab tests delay life-saving intervention</li>
                      <li>• No rapid, multiplex detection in saliva</li>
                      <li>• First responders need affordable, real-time tools</li>
                    </ul>
                  </div>
                  
                  <div className="ent-highlight-card ent-solutions">
                    <div className="ent-highlight-header">
                      <CheckCircle className="ent-highlight-icon ent-green-text" />
                      <h4 className="ent-highlight-title ent-green-text">OPIO-RX Innovation</h4>
                    </div>
                    <ul className="ent-highlight-list">
                      <li>• Rapid, multiplex saliva biosensor</li>
                      <li>• &lt;10-minute, semi-quantitative results at point-of-care</li>
                      <li>• Detects multiple key opioids (fentanyl, oxycodone, etc.)</li>
                      <li>• Enables immediate, data-driven decisions</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Market Size Analysis Section */}
        <section className="ent-section">
          <div className="ent-card ent-market-card">
            <div className="ent-card-header">
              <h3 className="ent-card-title ent-center">
                <TrendingUp className="ent-card-icon ent-emerald-text" />
                Market Size & Opportunity Analysis
              </h3>
              <p className="ent-card-subtitle">
                Comprehensive market sizing from global potential to targeted obtainable markets, 
                demonstrating clear pathways to revenue growth and market penetration
              </p>
            </div>
            <div className="ent-card-content">
              <div className="ent-market-content">
                <div className="ent-market-image-container">
                  <div className="ent-market-bg"></div>
                  <div className="ent-market-decoration">
                    <div className="ent-market-blob ent-market-blob-1"></div>
                    <div className="ent-market-blob ent-market-blob-2"></div>
                  </div>
                  
                  <div className="ent-market-image">
                    <img 
                      src="/images/entrepreneurship/entreimg2.png"
                      alt="Market Size Analysis: PAM ($41.2B), TAM ($8.5B), SAM ($1.2B), SOM ($100M) for OPIO-RX opioid detection technology"
                      className="ent-image"
                    />
                  </div>
                </div>

                {/* Strategic insights */}
                <div className="ent-insights">
                  <h4 className="ent-insights-title">Strategic Market Insights</h4>
                  <div className="ent-grid-3">
                    <div className="ent-insight-item">
                      <Globe className="ent-insight-icon ent-emerald-text" />
                      <h5 className="ent-insight-title ent-emerald-text">Global Reach</h5>
                      <p className="ent-insight-text">
                        $41.2B total market validates the massive global need for opioid detection solutions
                      </p>
                    </div>
                    <div className="ent-insight-item">
                      <Target className="ent-insight-icon ent-blue-text" />
                      <h5 className="ent-insight-title ent-blue-text">Focused Strategy</h5>
                      <p className="ent-insight-text">
                        $8.5B addressable market provides clear technological and commercial focus areas
                      </p>
                    </div>
                    <div className="ent-insight-item">
                      <Rocket className="ent-insight-icon ent-cyan-text" />
                      <h5 className="ent-insight-title ent-cyan-text">Launch Pathway</h5>
                      <p className="ent-insight-text">
                        $100M obtainable market represents achievable near-term revenue goals
                      </p>
                    </div>
                  </div>
                </div>

                {/* Business Model Canvas */}
                <div className="ent-business-model">
                  <div className="ent-business-model-header">
                    <div className="ent-business-model-decoration">
                      <div className="ent-business-model-blob ent-business-model-blob-1"></div>
                      <div className="ent-business-model-blob ent-business-model-blob-2"></div>
                    </div>
                    
                    <div className="ent-business-model-content">
                      <div className="ent-business-model-text">
                        <h3 className="ent-business-model-title">Business Model Canvas</h3>
                        <p className="ent-business-model-description">
                          Comprehensive framework mapping out key business components including value propositions, 
                          customer segments, revenue streams, and strategic partnerships for OPIO-RX's market entry.
                        </p>
                      </div>
                    </div>
                    
                    <div className="ent-business-model-image">
                      <img 
                        src="/images/entrepreneurship/entreimg4.png"
                        alt="Business Model Canvas for OPIO-RX: Comprehensive framework mapping value propositions, customer segments, revenue streams, and strategic partnerships"
                        className="ent-image ent-business-model-image-inner"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SWOT Analysis Section */}
        <section className="ent-section">
          <div className="ent-card ent-swot-card">
            <div className="ent-card-header ent-swot-header">
              <h3 className="ent-card-title ent-center ent-swot-title">
                <BarChart3 className="ent-card-icon ent-blue-text" />
                SWOT Analysis
              </h3>
              <p className="ent-card-subtitle ent-swot-subtitle">
                Strategic analysis of internal strengths and weaknesses, alongside external opportunities 
                and threats facing OPIO-RX in the competitive biosensor market
              </p>
            </div>
            <div className="ent-card-content ent-swot-content">
              <div className="ent-swot-content-inner">
                <div className="ent-swot-image-container">
                  <div className="ent-swot-bg"></div>
                  <div className="ent-swot-decoration">
                    <div className="ent-swot-blob ent-swot-blob-1"></div>
                    <div className="ent-swot-blob ent-swot-blob-2"></div>
                  </div>
                  
                  <div className="ent-swot-image">
                    <img 
                      src="/images/entrepreneurship/entreimg3.png"
                      alt="SWOT Analysis for OPIO-RX: Strengths include high opioid-specific accuracy and immediate results; Weaknesses include high initial cost and regulatory approval process; Opportunities include urgent market need and government funding; Threats include strong competition and insurance reimbursement challenges"
                      className="ent-image ent-swot-image-inner"
                    />
                  </div>
                </div>

                {/* Strategic implications */}
                <div className="ent-implications">
                  <h4 className="ent-implications-title">Strategic Implications</h4>
                  <div className="ent-grid-3">
                    <div className="ent-implication-item">
                      <Shield className="ent-implication-icon ent-green-text" />
                      <h5 className="ent-implication-title ent-green-text">Leverage Strengths</h5>
                      <p className="ent-implication-text">
                        Capitalize on superior accuracy and rapid results to establish market leadership
                      </p>
                    </div>
                    <div className="ent-implication-item">
                      <Target className="ent-implication-icon ent-blue-text" />
                      <h5 className="ent-implication-title ent-blue-text">Address Weaknesses</h5>
                      <p className="ent-implication-text">
                        Focus on cost optimization and streamlined regulatory pathways
                      </p>
                    </div>
                    <div className="ent-implication-item">
                      <Rocket className="ent-implication-icon ent-purple-text" />
                      <h5 className="ent-implication-title ent-purple-text">Seize Opportunities</h5>
                      <p className="ent-implication-text">
                        Exploit urgent market demand while building strategic partnerships
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Key Performance Indicators Section */}
        <section className="ent-section">
          <div className="ent-kpi-header">
            <h2 className="ent-kpi-title">
              Key Performance Indicators
            </h2>
            <p className="ent-kpi-subtitle">
              Comprehensive metrics ensuring sustainable growth and regulatory success across 
              regulatory, product, operational, and commercial domains
            </p>
          </div>

          <div className="ent-kpi-categories">
            {kpiCategories.map((category, categoryIndex) => (
              <div key={category.title} className={`ent-kpi-category ${getColorClasses(category.color).bg} ${getColorClasses(category.color).border}`}>
                <div className="ent-kpi-category-header">
                  <h3 className="ent-kpi-category-title">
                    <category.icon className={`ent-kpi-category-icon ${getColorClasses(category.color).text}`} />
                    <span className={getColorClasses(category.color).text}>{category.title}</span>
                  </h3>
                </div>
                <div className="ent-kpi-category-content">
                  <div className="ent-grid-2">
                    {category.metrics.map((metric, metricIndex) => (
                      <div key={metric.name} className="ent-metric-card">
                        <h4 className={`ent-metric-title ${getColorClasses(category.color).accent}`}>
                          {metric.name}
                        </h4>
                        <p className="ent-metric-description">
                          {metric.description}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* PESTLE Analysis Section */}
        <section className="ent-section">
          <div className="ent-pestle-header">
            <h2 className="ent-pestle-title">
              PESTLE Analysis
            </h2>
            <p className="ent-pestle-subtitle">
              Comprehensive strategic analysis of Political, Economic, Social, Technological, 
              Legal, and Environmental factors influencing OPIO-RX development and deployment
            </p>
          </div>

          <div className="ent-pestle-grid">
            {pestleFactors.map((factor, factorIndex) => (
              <div key={factor.title} className={`ent-pestle-card ${getColorClasses(factor.color).bg} ${getColorClasses(factor.color).border}`}>
                <div className="ent-pestle-card-header">
                  <h3 className="ent-pestle-card-title">
                    <factor.icon className={`ent-pestle-card-icon ${getColorClasses(factor.color).text}`} />
                    <span className={getColorClasses(factor.color).text}>{factor.title}</span>
                  </h3>
                </div>
                <div className="ent-pestle-card-content">
                  <div className="ent-pestle-points">
                    {factor.points.map((point, pointIndex) => (
                      <div key={pointIndex} className="ent-pestle-point">
                        <div className={`ent-pestle-point-dot ${getColorClasses(factor.color).text.replace('text-', 'bg-')}`}></div>
                        <p className="ent-pestle-point-text">
                          {point}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Strategic Summary */}
        <section className="ent-section">
          <div className="ent-card ent-summary-card">
            <div className="ent-card-header">
              <h3 className="ent-card-title ent-center">
                <Rocket className="ent-card-icon ent-blue-text" />
                Strategic Foundation for Success
              </h3>
            </div>
            <div className="ent-card-content">
              <div className="ent-grid-3 ent-summary-grid">
                <div className="ent-summary-item ent-summary-performance">
                  <TrendingUp className="ent-summary-icon ent-blue-text" />
                  <h4 className="ent-summary-item-title ent-blue-text">Performance Excellence</h4>
                  <p className="ent-summary-item-text">
                    Comprehensive KPI framework ensuring measurable success across all operational dimensions
                  </p>
                </div>
                
                <div className="ent-summary-item ent-summary-intelligence">
                  <Globe className="ent-summary-icon ent-purple-text" />
                  <h4 className="ent-summary-item-title ent-purple-text">Market Intelligence</h4>
                  <p className="ent-summary-item-text">
                    PESTLE analysis providing strategic insights for sustainable competitive advantage
                  </p>
                </div>
                
                <div className="ent-summary-item ent-summary-vision">
                  <Star className="ent-summary-icon ent-emerald-text" />
                  <h4 className="ent-summary-item-title ent-emerald-text">Vision Realization</h4>
                  <p className="ent-summary-item-text">
                    Clear mission and vision driving innovation toward global health impact
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
