import React from 'react'
import {
  Target,
  Rocket,
  TrendingUp,
  Shield,
  Users,
  CheckCircle,
  BarChart3,
  DollarSign,
  Zap,
  Globe,
  Building,
  AlertTriangle,
  Lightbulb,
  Scale,
  Leaf,
  Heart,
  Brain,
  Star
} from 'lucide-react'

// NOTE: Tailwind has been converted to normal CSS using the site's existing .ent-* classes (see App.css)

const kpiCategories = [
  {
    title: 'Regulatory and Quality KPIs',
    icon: Shield,
    color: 'blue',
    metrics: [
      { name: 'Regulatory Compliance Rate', description: 'Percentage of successful audits and inspections without violations' },
      { name: 'Complaint Rate', description: 'Number of customer complaints per 1,000 devices sold' },
      { name: 'Device Defect Rate', description: 'Frequency of device malfunctions or nonconformities per production batch' },
      { name: 'CAPA Effectiveness', description: 'Percentage of corrective and preventive actions that permanently resolve identified issues' }
    ]
  },
  {
    title: 'Product and Clinical KPIs',
    icon: Heart,
    color: 'green',
    metrics: [
      { name: 'Diagnostic Accuracy Rate', description: 'Proportion of accurate test results compared to total tests conducted' },
      { name: 'Clinical Trial Success Rate', description: 'Percentage of clinical studies achieving predefined safety, sensitivity, and specificity benchmarks' },
      { name: 'Limit of Detection (LoD) Consistency', description: 'Variability in LoD values across validated production batches' }
    ]
  },
  {
    title: 'Commercial and Market KPIs',
    icon: DollarSign,
    color: 'purple',
    metrics: [
      { name: 'Market Adoption Rate', description: 'Percentage of target customers or institutions adopting Opio-RX within a specified timeframe' },
      { name: 'Sales per Product Line', description: 'Revenue generated by each device configuration or deployment model' },
      { name: 'Gross Profit Margin', description: '(Revenue − Cost of Goods Sold) ÷ Revenue, expressed as a percentage' },
      { name: 'Customer Retention Rate', description: 'Share of clients who reorder consumables or renew service agreements' },
      { name: 'Customer Acquisition Cost (CAC)', description: 'Total marketing and sales expenditure per new customer acquired' }
    ]
  },
  {
    title: 'Operational KPIs',
    icon: Building,
    color: 'orange',
    metrics: [
      { name: 'Manufacturing Yield', description: 'Percentage of successfully produced units meeting all specifications' },
      { name: 'On-Time Delivery Rate', description: 'Orders fulfilled within the promised delivery schedule' },
      { name: 'Inventory Turnover Ratio', description: 'Efficiency of stock management and material utilization cycles' },
      { name: 'Customer Service Response Time', description: 'Average time taken to close technical or support queries' }
    ]
  },
  {
    title: 'Strategic and Innovation KPIs',
    icon: Lightbulb,
    color: 'cyan',
    metrics: [
      { name: 'Time to Market', description: 'Duration from R&D initiation to regulatory approval and commercial launch' },
      { name: 'Device Utilization Rate', description: 'Actual frequency of device use relative to expected operational capacity' },
      { name: 'R&D Productivity Index', description: 'Ratio of successful prototypes to total R&D projects undertaken' },
      { name: 'Intellectual Property (IP) Growth Rate', description: 'Number of new patents, trade secrets, or technology disclosures filed per year' }
    ]
  }
]

const pestleFactors = [
  {
    title: 'Political Factors',
    icon: Building,
    color: 'red',
    points: [
      'Government funding emphasis on combating opioid epidemic supports rapid diagnostic technologies',
      'Partnerships with law enforcement, public health agencies, and emergency responders',
      'Compliance with international drug control treaties (UN conventions) shapes deployment standards'
    ]
  },
  {
    title: 'Economic Factors',
    icon: DollarSign,
    color: 'green',
    points: [
      'Lower per-test costs vs. GC-MS enables scalable deployment in resource-limited settings',
      'Efficient production of aptamers and AuNP components supports competitive pricing',
      'Insurance reimbursement policies influence clinical adoption rates'
    ]
  },
  {
    title: 'Social Factors',
    icon: Users,
    color: 'blue',
    points: [
      'Rising societal concern about synthetic opioid abuse drives demand for rapid detection',
      'Non-invasive testing reduces stigma and improves public acceptance',
      'Informed consent and data privacy critical for maintaining community trust'
    ]
  },
  {
    title: 'Technological Factors',
    icon: Brain,
    color: 'purple',
    points: [
      'Aptamer engineering ensures high specificity for synthetic opioids',
      'FRET-AuNP paper-based platform with AI-powered quantification for point-of-care use',
      'Smartphone integration enhances field usability and data connectivity',
      'Stability optimization critical for shelf-life and storage under varied conditions'
    ]
  },
  {
    title: 'Legal Factors',
    icon: Scale,
    color: 'yellow',
    points: [
      'FDA clearance and CE marking required for medical device commercialization',
      'Legal frameworks for law enforcement use, including data admissibility standards',
      'Patent protection for aptamer sequences and biosensor designs',
      'HIPAA and GDPR compliance for patient data protection'
    ]
  },
  {
    title: 'Environmental Factors',
    icon: Leaf,
    color: 'emerald',
    points: [
      'Biodegradable paper substrates promote eco-friendly device lifecycle',
      'Reduced chemical reagent use and toxic waste vs. laboratory methods',
      'Low-power optical detection minimizes environmental footprint',
      'Potential for monitoring opioid contamination in water and soil'
    ]
  }
]

const colorToClass = {
  blue: 'ent-card--blue',
  green: 'ent-card--green',
  purple: 'ent-card--purple',
  orange: 'ent-card--orange',
  cyan: 'ent-card--cyan',
  red: 'ent-card--red',
  emerald: 'ent-card--emerald',
  yellow: 'ent-card--yellow'
}

const SectionCard = ({ title, Icon, children, color }) => (
  <div className={`ent-card ${colorToClass[color] || ''}`}>
    <div className="ent-card-header">
      <Icon size={24} className="ent-card-icon" />
      <h3>{title}</h3>
    </div>
    <div className="ent-card-content">{children}</div>
  </div>
)

export default function EntrepreneurshipPage() {
  return (
    <div className="ent-page">
      {/* Hero */}
      <section className="ent-hero">
        <div className="ent-hero-inner">
          <div className="ent-badge"><BarChart3 size={18} /> Business Strategy & Innovation</div>
          <h1 className="ent-hero-title">Entrepreneurship</h1>
          <h2 className="ent-hero-sub">Building the Future of Opioid Detection</h2>
          <p className="ent-hero-desc">Strategic vision, measurable performance, and comprehensive market analysis driving sustainable innovation in healthcare technology.</p>
        </div>
      </section>

      <div className="ent-container">
        {/* Vision & Mission */}
        <section className="ent-grid ent-grid-2">
          <SectionCard title="Vision" Icon={Eye} color="blue">
            <p>To become the trusted global standard in opioid detection technology, recognized for pioneering multiplex diagnostic platforms that blend scientific excellence with commercial viability.</p>
          </SectionCard>
          <SectionCard title="Mission" Icon={Target} color="purple">
            <p>Deliver industry-leading, scalable biosensors for rapid, on-site synthetic opioid detection that empower healthcare providers, emergency responders, and public safety organizations globally.</p>
          </SectionCard>
        </section>

        {/* Problem & Solution */}
        <section className="ent-section">
          <SectionCard title="Problem & Solution Overview" Icon={Zap} color="cyan">
            <div className="ent-split">
              <div className="ent-tile ent-tile--danger">
                <div className="ent-tile-head"><AlertTriangle size={18} /> Critical Challenges</div>
                <ul>
                  <li>Synthetic opioid overdose crisis</li>
                  <li>Slow lab tests delay life-saving intervention</li>
                  <li>No rapid, multiplex detection in saliva</li>
                  <li>First responders need affordable, real-time tools</li>
                </ul>
              </div>
              <div className="ent-tile ent-tile--success">
                <div className="ent-tile-head"><CheckCircle size={18} /> OPIO‑RX Innovation</div>
                <ul>
                  <li>Rapid, multiplex saliva biosensor</li>
                  <li>&lt;10-minute, semi-quantitative results at point-of-care</li>
                  <li>Detects multiple key opioids (fentanyl, oxycodone, etc.)</li>
                  <li>Enables immediate, data-driven decisions</li>
                </ul>
              </div>
            </div>
          </SectionCard>
        </section>

        {/* KPI Categories */}
        <section className="ent-section">
          <h2 className="ent-section-title">Key Performance Indicators</h2>
          <div className="ent-grid ent-grid-1">
            {kpiCategories.map((cat) => (
              <SectionCard key={cat.title} title={cat.title} Icon={cat.icon} color={cat.color}>
                <div className="ent-metrics">
                  {cat.metrics.map((m) => (
                    <div key={m.name} className="ent-metric">
                      <div className="ent-metric-name">{m.name}</div>
                      <div className="ent-metric-desc">{m.description}</div>
                    </div>
                  ))}
                </div>
              </SectionCard>
            ))}
          </div>
        </section>

        {/* PESTLE */}
        <section className="ent-section">
          <h2 className="ent-section-title">PESTLE Analysis</h2>
          <div className="ent-grid ent-grid-2">
            {pestleFactors.map((f) => (
              <SectionCard key={f.title} title={f.title} Icon={f.icon} color={f.color}>
                <ul className="ent-list">
                  {f.points.map((p, i) => (<li key={i}>{p}</li>))}
                </ul>
              </SectionCard>
            ))}
          </div>
        </section>

        {/* Strategic Summary */}
        <section className="ent-grid ent-grid-3">
          <SectionCard title="Performance Excellence" Icon={TrendingUp} color="blue">
            <p>Comprehensive KPI framework ensuring measurable success across all operational dimensions.</p>
          </SectionCard>
          <SectionCard title="Market Intelligence" Icon={Globe} color="purple">
            <p>PESTLE analysis providing strategic insights for sustainable competitive advantage.</p>
          </SectionCard>
          <SectionCard title="Vision Realization" Icon={Star} color="green">
            <p>Clear mission and vision driving innovation toward global health impact.</p>
          </SectionCard>
        </section>
      </div>
    </div>
  )
}
